# Generated by Django 3.2 on 2024-08-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_assign_point_and_preference_senior'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='duty_status_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='duty_status',
            field=models.BooleanField(default=False),
        ),
    ]
