# Generated by Django 3.2 on 2024-08-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20240829_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='spouse_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
