# Generated by Django 3.2 on 2024-08-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_appointment_spouse_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='location',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='building',
            name='rent_charge',
            field=models.IntegerField(default=0),
        ),
    ]
